dubbo:
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://10.1.60.21
  cloud:
    # The subscribed services in consumer side
    subscribed-services: ${provider.application.name}
  protocols:
    dubbo:
      port: -1
  consumer:
    check: false

server:
  port: 18081

provider:
  application:
    name: spring-cloud-alibaba-dubbo-provider