dubbo:
  scan:
    base-packages: org.example.service
  protocols:
    dubbo:
      name: dubbo
      port: -1
    rest:
      name: rest
      port: 9090
      server: netty
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://10.1.60.21
